"""Add start_date to scenarios

Revision ID: 23d85b64d431
Revises: f2d509a771a9
Create Date: 2026-01-17 21:17:55.971798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d85b64d431'
down_revision = 'f2d509a771a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
