"""Update weight column for probability calc v1

Revision ID: 336cf1f1c6c4
Revises: a4954472652d
Create Date: 2026-01-19 18:44:13.172535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336cf1f1c6c4'
down_revision = 'a4954472652d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_events', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_events', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.NUMERIC(precision=5, scale=3),
               existing_nullable=True)

    # ### end Alembic commands ###
