"""named actor to scenario

Revision ID: 3bb578d2acf7
Revises: 0ff98f1962bf
Create Date: 2026-01-27 20:54:50.052151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bb578d2acf7'
down_revision = '0ff98f1962bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('named_actor', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'actors', ['named_actor'], ['actor_id'])

    with op.batch_alter_table('tracked_actors', schema=None) as batch_op:
        batch_op.alter_column('tracked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('tracked_actors_actor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tracked_actors_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'actors', ['actor_id'], ['actor_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tracked_institutions', schema=None) as batch_op:
        batch_op.alter_column('tracked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('tracked_institutions_institution_code_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tracked_institutions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'institutions', ['institution_code'], ['institution_code'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('tracked_positions', schema=None) as batch_op:
        batch_op.alter_column('tracked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('tracked_positions_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tracked_positions_position_code_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'positions', ['position_code'], ['position_code'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_positions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tracked_positions_position_code_fkey'), 'positions', ['position_code'], ['position_code'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tracked_positions_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('tracked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tracked_institutions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tracked_institutions_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tracked_institutions_institution_code_fkey'), 'institutions', ['institution_code'], ['institution_code'], ondelete='CASCADE')
        batch_op.alter_column('tracked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tracked_actors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tracked_actors_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tracked_actors_actor_id_fkey'), 'actors', ['actor_id'], ['actor_id'], ondelete='CASCADE')
        batch_op.alter_column('tracked_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('named_actor')

    # ### end Alembic commands ###
