"""institutional and positional nesting for reporting

Revision ID: 7b452872ed84
Revises: d4673fc7b09e
Create Date: 2026-02-09 15:14:08.052027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b452872ed84'
down_revision = 'd4673fc7b09e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_institution_code', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_institutions_parent_institution_code'), ['parent_institution_code'], unique=False)
        batch_op.create_foreign_key(None, 'institutions', ['parent_institution_code'], ['institution_code'])

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reports_to_position_code', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_positions_reports_to_position_code'), ['reports_to_position_code'], unique=False)
        batch_op.create_foreign_key(None, 'positions', ['reports_to_position_code'], ['position_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_positions_reports_to_position_code'))
        batch_op.drop_column('reports_to_position_code')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_institutions_parent_institution_code'))
        batch_op.drop_column('parent_institution_code')

    # ### end Alembic commands ###
