"""Resolution fields to scenarios

Revision ID: a4954472652d
Revises: 23d85b64d431
Create Date: 2026-01-18 12:58:10.733414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4954472652d'
down_revision = '23d85b64d431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_outcome', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resolution_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('resolution_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_column('resolution_notes')
        batch_op.drop_column('resolution_date')
        batch_op.drop_column('resolution_outcome')

    # ### end Alembic commands ###
