"""actor relationship table

Revision ID: d4673fc7b09e
Revises: 3bb578d2acf7
Create Date: 2026-02-02 16:17:14.405538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4673fc7b09e'
down_revision = '3bb578d2acf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_relationships',
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('actor_id_primary', sa.String(length=20), nullable=False),
    sa.Column('actor_id_related', sa.String(length=20), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('relationship_label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actor_id_primary != actor_id_related', name='chk_different_actors'),
    sa.CheckConstraint('confidence_level IS NULL OR (confidence_level >= 1 AND confidence_level <= 5)', name='chk_confidence_range'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='chk_relationship_dates'),
    sa.ForeignKeyConstraint(['actor_id_primary'], ['actors.actor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_id_related'], ['actors.actor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id'),
    sa.UniqueConstraint('actor_id_primary', 'actor_id_related', 'relationship_label', name='uq_relationship')
    )
    with op.batch_alter_table('actor_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_relationships_actor_id_primary'), ['actor_id_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_actor_relationships_actor_id_related'), ['actor_id_related'], unique=False)
        batch_op.create_index(batch_op.f('ix_actor_relationships_relationship_type'), ['relationship_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_relationships_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_actor_relationships_actor_id_related'))
        batch_op.drop_index(batch_op.f('ix_actor_relationships_actor_id_primary'))

    op.drop_table('actor_relationships')
    # ### end Alembic commands ###
