"""add narratives tables

Revision ID: ebd94fc0fbd4
Revises: 7b452872ed84
Create Date: 2026-02-20 09:56:44.861418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd94fc0fbd4'
down_revision = '7b452872ed84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('narrative_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('res_horizon', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_trend', sa.Numeric(), nullable=True),
    sa.Column('long_trend', sa.Numeric(), nullable=True),
    sa.Column('pos_pressure', sa.Numeric(), nullable=True),
    sa.Column('neg_pressure', sa.Numeric(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('min_mod_count', sa.Integer(), nullable=True),
    sa.Column('maj_crit_count', sa.Integer(), nullable=True),
    sa.Column('dom_action', sa.String(length=10), nullable=True),
    sa.Column('dom_region', sa.String(length=10), nullable=True),
    sa.Column('dom_entity', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('narrative_code')
    )
    op.create_table('narrative_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrative_code', sa.String(length=50), nullable=False),
    sa.Column('entity_code', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('action_code', sa.String(length=10), nullable=False),
    sa.Column('polarity', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['narrative_code'], ['narratives.narrative_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marked_scenario_id', sa.Integer(), nullable=False),
    sa.Column('narrative_code', sa.String(length=50), nullable=False),
    sa.Column('relationship', sa.Boolean(), nullable=False),
    sa.Column('potency', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['marked_scenario_id'], ['marked_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['narrative_code'], ['narratives.narrative_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marked_scenario_id', 'narrative_code', name='uq_narrative_scenario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('narrative_scenarios')
    op.drop_table('narrative_resolutions')
    op.drop_table('narratives')
    # ### end Alembic commands ###
