"""Create Scenarios

Revision ID: f2d509a771a9
Revises: 87f5f758487f
Create Date: 2026-01-17 14:47:51.387511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d509a771a9'
down_revision = '87f5f758487f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_scenario_code'), ['scenario_code'], unique=True)

    op.create_table('marked_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('initial_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('probability_history', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marked_scenario_id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('linked_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_code'], ['control_frame.event_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['marked_scenario_id'], ['marked_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marked_scenario_id', 'event_code', name='uq_marked_scenario_event')
    )
    with op.batch_alter_table('scenario_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_events_event_code'), ['event_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenario_events_marked_scenario_id'), ['marked_scenario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_events_marked_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_scenario_events_event_code'))

    op.drop_table('scenario_events')
    op.drop_table('marked_scenarios')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_scenario_code'))

    op.drop_table('scenarios')
    # ### end Alembic commands ###
