"""update narratives model

Revision ID: f314f211b873
Revises: ebd94fc0fbd4
Create Date: 2026-02-20 12:38:14.030546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f314f211b873'
down_revision = 'ebd94fc0fbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('narrative_resolutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('narrative_scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('narratives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_trend', sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('res_horizon',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('narratives', schema=None) as batch_op:
        batch_op.alter_column('res_horizon',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('initial_trend')

    with op.batch_alter_table('narrative_scenarios', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('narrative_resolutions', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
